import Head from "next/head";
import styles from "@/styles/home.module.scss";
import logoImg from "../../../../public/logo.svg";
import Image from "next/image";
import { Input } from "@/components/ui/Input";
import Button from "@/components/ui/Button";
import Link from "next/link";
import { useAuth } from "@/contexts/AuthContext";
import { canSSRGuest } from "@/utils/canSSRGuest";
import useSignIn from "../../../hooks/useSignIn";

export default function SignIn() {
  const { formik } = useSignIn();
  const { loading } = useAuth();

  const { errors, setFieldValue, values, handleSubmit } = formik;

  return (
    <>
      <Head>
        <title>Pizzaria - Faça seu login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.containerCenter}>
        <Image src={logoImg} alt="Logotipo Pizzaria" />
        <div className={styles.login}>
          <form onSubmit={handleSubmit}>
            <Input
              placeholder="Digite seu e-mail"
              type="text"
              value={values.email}
              onChange={(e) => setFieldValue("email", e.target.value)}
              errors={errors.email}
            />
            <Input
              placeholder="Digite sua senha"
              type="password"
              value={values.password}
              onChange={(e) => setFieldValue("password", e.target.value)}
              errors={errors.password}
            />
            <Button loading={loading}>Acessar</Button>
          </form>
          <Link href="signup" className={styles.text}>
            Não possui conta? Cadastre-se
          </Link>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = canSSRGuest(async (ctx) => {
  return {
    props: {},
  };
});
